// mongodb doesnt have transactions, search mongodb 2 phase commits to learn more
// using a library that gives an illusion of transactions
// fawn is the name

const Fawn = require("fawn");
const mongoose = require("mongoose");

Fawn.init(mongoose);
//transactions
try {
  new Fawn.Task()
    .save("rentals", rental) //pass the name of the collection and the object you wanna save
    .update("movies", { _id: movie._id }, { $inc: { numberInStock: -1 } }) //2nd arg is the movies that we want to update and third is the update object
    .run(); // finally call run
} catch (error) {
  res.status(500).send("something failed");
}

/**
 * id : 24char string, every 2 char = byte
 *  12 bytes
 *      1st 4 bytes : timestamp
 *      3 bytes : machine identifiers
 *      2 bytes : process identifier
 *      3 bytes : counter
 */

/**
 * 1 byte = 8bits
 * 2^8 = 256
 * 2^24 = 16M
 * all ids are almost unique
 *
 * Driver->Mongodb id is generated by Driver
 * mongoose is abstraction over the driver
 */

const id = new mongoose.Types.ObjectId();
console.log("manually created id :", id);
//some methods
//id.getTimestamp()

const isValid = mongoose.Types.ObjectId.isValid("1234");
console.log(isValid); // out print false
